### ISSUE TITLE
如何插入图片到excel？

### ISSUE THREAD

**Issue by Xcent-xl** [li-yu/SQLiteToExcel#1]
把图片用blob格式存入sqlite，如何导入到excel里面？直接导入会报错说blob不是string类型，有办法将图片插入到生成的excel里面吗

**Comment by li-yu** [comment]
@Xcent-xl  Hi，由于项目年代久远，今天抽空完善了下，已更新到了 v1.0.2，解决了 blob 导出报错的bug，请测试验证，谢谢。
