### ISSUE TITLE
1.0.8版本setTables（String...tables）失效

### ISSUE THREAD

**Issue by ShenChaohui** [li-yu/SQLiteToExcel#11]
1.0.8版本里
public String start() {
        try {
            if (tables == null || tables.size() == 0) {
                tables = getTablesName(database);
            }
            return exportTables(getTablesName(database), fileName);
        } catch (Exception e) {
            if (database != null && database.isOpen()) {
                database.close();
            }
            return null;
        }
    }
return 的永远是所有的表

**Comment by li-yu** [comment]
@ShenChaohui 感谢回复，已确认此 bug，你可以 pull request 或者我晚点 fix

**Comment by li-yu** [comment]
Fixed
