### ISSUE TITLE
关于加密

### ISSUE THREAD

**Issue by AIlll** [li-yu/SQLiteToExcel#3]
请问下导出表格能否进行加密呢

**Comment by li-yu** [comment]
@AIlll Apache POI 其实提供了加解密的相关方法，不过本库暂未添加该功能，近期抽时间加上，感谢反馈。

**Comment by AIlll** [comment]
@li-yu 再请问一下，android能不能对Excel表格添加修改权限这种操作，就是只能查看不能修改

**Comment by li-yu** [comment]
@AIlll 翻看了下文档，是有接口的，sheet.protectSheet(String password); 你可以试试

**Comment by AIlll** [comment]
好的谢谢

**Comment by li-yu** [comment]
@AIlll v1.0.5 加密功能已完成，有时间可以测试下
