### ISSUE TITLE
录入出错

### ISSUE THREAD

**Issue by Rairmmd** [li-yu/SQLiteToExcel#5]
感谢开源，我导出时设置了密码   然后录入是没有相应的添加密码的设置，会导致录入出错

**Comment by li-yu** [comment]
@Rairmmd 能否提供下出错 log 以及录入的 excel 文档（如果可以的话），我排查下

**Comment by li-yu** [comment]
@Rairmmd 前段时间发现不同的 office 软件对于 xls 加密时，poi 处理有些异常，所以导入时暂时没有添加解密的功能。我抽时间再研究下。

**Comment by li-yu** [comment]
@Rairmmd v1.0.6 新增 setEncryptKey(String key) 方法用于解密文档，如果有时间麻烦测试验证下:wink:

**Comment by Rairmmd** [comment]
@li-yu  非常感谢

**Comment by li-yu** [comment]
@Rairmmd 结果如何？如果没有什么问题，麻烦 close the issue，谢谢！
