### ISSUE TITLE
又要麻烦你了

### ISSUE THREAD

**Issue by Rairmmd** [li-yu/SQLiteToExcel#7]
导入的时候要是可以指定字段名就好了，不然不知道怎么查数据了。

**Comment by li-yu** [comment]
@Rairmmd Excel 导入 SQLite 时，默认取 excel 中 sheet 的第一行作为数据库表的列名，excel 样式可以参考[这里](https://github.com/li-yu/SQLiteToExcel/blob/master/app/src/main/assets/user.xls)。
在 excel 文档里事先写好一个列名，比在代码里重新指定字段名要自由的多。如果这样还不能解决你的需求，请麻烦详细描述下你的应用场景，谢谢。

**Comment by Rairmmd** [comment]
@li-yu Supplied password is invalid for salterifiererifierHash

**Comment by li-yu** [comment]
@Rairmmd 如果可以，能否提供下 excel 文档，我这边做下验证
