### ISSUE TITLE
sqlite导出excel时，能不能对某一列的数据进行转换？

### ISSUE THREAD

**Issue by yeshiyuan00** [li-yu/SQLiteToExcel#9]
比如某一列存的是时间戳，转换成可阅读的时间格式，或者0、1转换为成功、失败。

**Comment by li-yu** [comment]
可以的，使用自定义 SQL 导出，setSQL(sql)
1. 时间戳可以使用 SQLite Date 函数，例如：SELECT datetime(1092941466, 'unixepoch');
2. 0、1转换为成功、失败，可以使用 case when then 语句：
例如：SELECT CASE Result WHEN 0 THEN '成功'  WHEN 1 THEN '失败'

**Comment by yeshiyuan00** [comment]
我试试，谢谢指点！
